export const INIT_FETCH_SCREEN = "INIT_FETCH_SCREEN"
export const FETCH_SCREEN_SUCCESS = "FETCH_SCREEN_SUCCESS"
export const FETCH_SCREEN_FAILED = "FETCH_SCREEN_FAILED"

export const INIT_ADD_SCREEN = "INIT_ADD_SCREEN"
export const ADD_SCREEN_SUCCESS = "ADD_SCREEN_SUCCESS"
export const ADD_SCREEN_FAILED = "ADD_SCREEN_FAILED"

export const INIT_UPDATE_SCREEN = "INIT_UPDATE_SCREEN"
export const UPDATE_SCREEN_SUCCESS = "UPDATE_SCREEN_SUCCESS"
export const UPDATE_SCREEN_FAILED = "UPDATE_SCREEN_FAILED"

export const INIT_DELETE_SCREEN = "INIT_DELETE_SCREEN"
export const DELETE_SCREEN_SUCCESS = "DELETE_SCREEN_SUCCESS"
export const DELETE_SCREEN_FAILED = "DELETE_SCREEN_FAILED"

export const INIT_SINGLE_SCREEN = "INIT_SINGLE_SCREEN"
export const SINGLE_SCREEN_SUCCESS = "SINGLE_SCREEN_SUCCESS"
export const SINGLE_SCREEN_FAILED = "SINGLE_SCREEN_FAILED"