export const INIT_FETCH_THEATER_SCREEN = "INIT_FETCH_THEATER_SCREEN"
export const FETCH_SCREEN_THEATER_SUCCESS = "FETCH_SCREEN_THEATER_SUCCESS"
export const FETCH_SCREEN_THEATER_FAILED = "FETCH_SCREEN_THEATER_FAILED"

export const INIT_ADD_THEATER_SCREEN = "INIT_ADD_THEATER_SCREEN"
export const ADD_SCREEN_THEATER_SUCCESS = "ADD_SCREEN_THEATER_SUCCESS"
export const ADD_SCREEN_THEATER_FAILED = "ADD_SCREEN_THEATER_FAILED"

export const INIT_UPDATE_THEATER_SCREEN = "INIT_UPDATE_THEATER_SCREEN"
export const UPDATE_SCREEN_THEATER_SUCCESS = "UPDATE_SCREEN_THEATER_SUCCESS"
export const UPDATE_SCREEN_THEATER_FAILED = "UPDATE_SCREEN_THEATER_FAILED"

export const INIT_DELETE_THEATER_SCREEN = "INIT_DELETE_THEATER_SCREEN"
export const DELETE_SCREEN_THEATER_SUCCESS = "DELETE_SCREEN_THEATER_SUCCESS"
export const DELETE_SCREEN_THEATER_FAILED = "DELETE_SCREEN_THEATER_FAILED"

export const INIT_SINGLE_THEATER_SCREEN = "INIT_SINGLE_THEATER_SCREEN"
export const SINGLE_SCREEN_THEATER_SUCCESS = "SINGLE_SCREEN_THEATER_SUCCESS"
export const SINGLE_SCREEN_THEATERFAILED = "SINGLE_SCREEN_THEATERFAILED"