export const INIT_FETCH_USER = "INIT_FETCH_USER"
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const FETCH_USER_FAILED = "FETCH_USER_FAILED"

export const INIT_ADD_USER = "INIT_ADD_USER"
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS"
export const ADD_USER_FAILED = "ADD_USER_FAILED"

export const INIT_UPDATE_USER = "INIT_UPDATE_USER"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED"

export const INIT_DELETE_USER = "INIT_DELETE_USER"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAILED = "DELETE_USER_FAILED"

export const INIT_SINGLE_USER = "INIT_SINGLE_USER"
export const SINGLE_USER_SUCCESS = "SINGLE_USER_SUCCESS"
export const SINGLE_USER_FAILED = "SINGLE_USER_FAILED"

export const INIT_SINGLE_LOGIN = "INIT_SINGLE_LOGIN"
export const SINGLE_LOGIN_SUCCESS = "SINGLE_LOGIN_SUCCESS"
export const SINGLE_LOGIN_FAILED = "SINGLE_LOGIN_FAILED"

export const INIT_FETCH_GETALLUSER = "INIT_FETCH_GETALLUSER"
export const FETCH_GETALLUSER_SUCCESS = "FETCH_GETALLUSER_SUCCESS"
export const FETCH_GETALLUSER_FAILED = "FETCH_GETALLUSER_FAILED"

export const INIT_FETCH_GETALLTHEATER = "INIT_FETCH_GETALLTHEATER"
export const FETCH_GETALLTHEATER_SUCCESS = "FETCH_GETALLTHEATER_SUCCESS"
export const FETCH_GETALLTHEATER_FAILED = "FETCH_GETALLTHEATER_FAILED"

export const INIT_SINGLE_FETCHPROFILE = "INIT_SINGLE_FETCHPROFILE"
export const SINGLE_FETCHPROFILE_SUCCESS = "SINGLE_FETCHPROFILE_SUCCESS"
export const SINGLE_FETCHPROFILE_FAILED = "SINGLE_FETCHPROFILE_FAILED"

export const INIT_UPDATE_UPDATEPROFILE = "INIT_UPDATE_UPDATEPROFILE"
export const UPDATE_UPDATEPROFILE_SUCCESS = "UPDATE_UPDATEPROFILE_SUCCESS"
export const UPDATE_UPDATEPROFILE_FAILED = "UPDATE_UPDATEPROFILE_FAILED"

export const INIT_SINGLE_FETCHDASHBOARDRECORD = "INIT_SINGLE_FETCHDASHBOARDRECORD"
export const SINGLE_FETCHDASHBOARDRECORD_SUCCESS = "SINGLE_FETCHDASHBOARDRECORD_SUCCESS"
export const SINGLE_FETCHDASHBOARDRECORD_FAILED = "SINGLE_FETCHDASHBOARDRECORD_FAILED"

export const INIT_SINGLE_CHANGEPASSWORD = "INIT_SINGLE_CHANGEPASSWORD"
export const SINGLE_CHANGEPASSWORD_SUCCESS = "SINGLE_CHANGEPASSWORD_SUCCESS"
export const SINGLE_CHANGEPASSWORD_FAILED = "SINGLE_CHANGEPASSWORD_FAILED"